services:
  - type: web
    name: civiceye-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:

      - key: NODE_ENV
        value: production
      - key: DB_URL
        sync: false
      - key: KEY
        sync: false
      - key: SALT
        value: 12
      - key: CLIENT_URL
        sync: false
